"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY environment variable is not set!")

POSH_TRAINING_VIDEO_URL = os.getenv(
    "POSH_TRAINING_VIDEO_URL",
    "https://website-data-593333832687-ap-south-1-an.s3.ap-south-1.amazonaws.com/Hanuai%20Website/POSH_Training_Video.mp4",
)

# FIX #5: Default to False so production deployments without .env are safe
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

allowed_hosts_env = os.getenv("ALLOWED_HOSTS")
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",") if host.strip()]
else:
    if not DEBUG:
        ALLOWED_HOSTS = [
            "openhandsolutions.com",
            "www.openhandsolutions.com",
        ]
    else:
        ALLOWED_HOSTS = [
            "127.0.0.1",
            "localhost",
        ]

# Production site URL — used in emails sent to employees (login links, etc.)
SITE_URL = os.getenv("SITE_URL", "https://openhandsolutions.com")

# Session expires when the browser is closed (no persistent cookie)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# FIX #8: SameSite=Strict prevents session cookie from being sent on cross-site requests
# FIX #15: Explicitly mark session cookie as HttpOnly (JS cannot read it)
SESSION_COOKIE_SAMESITE = "Strict"
CSRF_COOKIE_SAMESITE = "Strict"
SESSION_COOKIE_HTTPONLY = True

# Production Security Settings
csrf_trusted_origins_env = os.getenv("CSRF_TRUSTED_ORIGINS")
if csrf_trusted_origins_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_trusted_origins_env.split(",") if origin.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [
        "https://openhandsolutions.com",
        "https://www.openhandsolutions.com",
        "http://127.0.0.1:8000",
        "http://localhost:8000",
    ]
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "home",
    "chat",
    "posh",
    "pocso",
    "django_extensions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "home.middleware.TabCloseSessionMiddleware",
    # FIX #6: Protect sensitive /media/ paths from unauthenticated access
    "home.middleware.MediaAuthMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # FIX #9: Content-Security-Policy and other hardening headers
    "home.middleware.SecurityHeadersMiddleware",
]

# Security settings (production vs development safe)

SECURE_SSL_REDIRECT = not DEBUG

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

else:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Clickjacking protection
X_FRAME_OPTIONS = "DENY"
ROOT_URLCONF = "OHS.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR, "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "OHS.wsgi.application"
NPM_BIN_PATH = r"/usr/bin/npm"
# "C:/Program Files/nodejs/npm.cmd"  --for windows--


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# settings.py
AUTH_USER_MODEL = "home.User"
# Assumes your app name is 'home'. If it's different, change 'home' to your app name.
LOGIN_REDIRECT_URL = "login_redirect"

# When they log out, send them to the home page
LOGOUT_REDIRECT_URL = "home"

# If a user tries to access a restricted page, send them to login
LOGIN_URL = "login"


# backend authentication
AUTHENTICATION_BACKENDS = [
    "home.backends.EmailOrUsernameModelBackend",
    "django.contrib.auth.backends.ModelBackend",
]
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",  # Without manifest
    },
}

# WhiteNoise settings for high-performance static asset caching
WHITENOISE_MAX_AGE = 31536000  # 1 year in seconds

# Email Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")  # Update if using different email provider
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "openhandpvtltd@gmail.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Open Hand Solutions <openhandpvtltd@gmail.com>")
SUPPORT_EMAIL = os.getenv("SUPPORT_EMAIL", "openhandpvtltd@gmail.com")


# Logging — writes certificate and general errors to a rotating log file
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(BASE_DIR / "logs" / "django.log"),
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 3,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "home.certificate": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "home": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": True,
        },
    },
}