# Generated by Django 5.2.7 on 2026-01-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual Subscriber'), ('COMPANY_ADMIN', 'Company Admin'), ('EMPLOYEE', 'Company Employee')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'user')},
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('organization__isnull', True)), models.Q(('user__isnull', True), ('organization__isnull', False)), _connector='OR'), name='subscription_owner_constraint'),
        ),
    ]
