# Generated by Django 6.0 on 2026-01-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_subscription_subscription_owner_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='subscription_owner_constraint',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='check_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('user__isnull', False)), models.Q(('organization__isnull', False), ('user__isnull', True)), _connector='OR'), name='subscription_owner_constraint'),
        ),
    ]
