# Generated by Django 6.0.1 on 2026-02-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_trainingmodule_organization_organization_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingmodule",
            name="ppt_file",
            field=models.FileField(blank=True, null=True, upload_to="training_ppts/"),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="training_videos/"),
        ),
    ]
