# Generated by Django 6.0.2 on 2026-03-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_assessmentprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
