# Generated by Django 6.0.3 on 2026-04-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_organization_default_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
    ]
