# Generated by Django 6.0.3 on 2026-04-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_organization_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo_width",
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo_x",
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo_y",
            field=models.FloatField(default=2.0),
        ),
    ]
