# Generated by Django 6.0.3 on 2026-04-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_organization_logo_width_organization_logo_x_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="POSHRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True, null=True)),
                ("employee_count", models.IntegerField()),
                ("trained_employee_count", models.IntegerField()),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("OFFLINE", "Offline"),
                            ("VIRTUAL", "Virtual"),
                            ("E_LEARNING", "E-learning"),
                        ],
                        max_length=20,
                    ),
                ),
                ("has_posh_policy", models.BooleanField(default=False)),
                ("has_ic", models.BooleanField(default=False)),
                ("ic_last_training_year", models.IntegerField(blank=True, null=True)),
                (
                    "ic_training_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OFFLINE", "Offline"),
                            ("VIRTUAL", "Virtual"),
                            ("E_LEARNING", "E-learning"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("external_member_support", models.BooleanField(default=False)),
                ("she_box_registered", models.BooleanField(default=False)),
                ("nodal_officer_appointed", models.BooleanField(default=False)),
                ("annual_report_submitted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
