# Generated by Django 6.0.3 on 2026-04-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_poshregistration_is_paid_poshregistration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshregistration',
            name='training_type',
            field=models.CharField(blank=True, choices=[('OFFLINE', 'Offline'), ('VIRTUAL', 'Virtual'), ('E_LEARNING', 'E-learning')], max_length=20, null=True),
        ),
    ]
