# Generated by Django 6.0.3 on 2026-04-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_poshregistration_training_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poshregistration",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
