# Generated by Django 6.0.3 on 2026-04-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_poshregistration_contact_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="poshregistration",
            name="last_training_year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
