# Generated by Django 6.0.3 on 2026-04-08 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_poshregistration_ic_last_training_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("INDIVIDUAL", "Individual Subscriber"),
                    ("COMPANY_ADMIN", "Company Admin"),
                    ("EMPLOYEE", "Company Employee"),
                    ("ACCOUNTS", "Accounts Department"),
                ],
                default="INDIVIDUAL",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="POSHPricingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_platform_fee",
                    models.DecimalField(
                        decimal_places=2, default=5000.0, max_digits=10
                    ),
                ),
                (
                    "price_tier_1_max",
                    models.IntegerField(
                        default=25, help_text="Max employees for Tier 1"
                    ),
                ),
                (
                    "price_tier_1_rate",
                    models.DecimalField(decimal_places=2, default=163.0, max_digits=8),
                ),
                (
                    "price_tier_2_max",
                    models.IntegerField(
                        default=100, help_text="Max employees for Tier 2"
                    ),
                ),
                (
                    "price_tier_2_rate",
                    models.DecimalField(decimal_places=2, default=154.0, max_digits=8),
                ),
                (
                    "price_tier_3_max",
                    models.IntegerField(
                        default=200, help_text="Max employees for Tier 3"
                    ),
                ),
                (
                    "price_tier_3_rate",
                    models.DecimalField(decimal_places=2, default=145.0, max_digits=8),
                ),
                (
                    "price_tier_4_max",
                    models.IntegerField(
                        default=500, help_text="Max employees for Tier 4"
                    ),
                ),
                (
                    "price_tier_4_rate",
                    models.DecimalField(decimal_places=2, default=127.0, max_digits=8),
                ),
                (
                    "price_tier_5_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=127.0,
                        help_text="Rate for 500+ employees",
                        max_digits=8,
                    ),
                ),
                (
                    "fee_no_posh_policy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Extra fee if no POSH policy in place",
                        max_digits=10,
                    ),
                ),
                (
                    "fee_no_ic",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Extra fee if no Internal Committee",
                        max_digits=10,
                    ),
                ),
                (
                    "fee_no_external_member",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Extra fee if external member support is required",
                        max_digits=10,
                    ),
                ),
                (
                    "fee_not_she_box_registered",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Extra fee if not SHe Box registered",
                        max_digits=10,
                    ),
                ),
                (
                    "fee_annual_report_not_submitted",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Extra fee if annual report not submitted",
                        max_digits=10,
                    ),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=18.0,
                        help_text="GST percentage to apply",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only ONE active config should exist"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "POSH Pricing Configuration",
                "verbose_name_plural": "POSH Pricing Configurations",
            },
        ),
    ]
