# Generated by Django 6.0.3 on 2026-04-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_poshpricingconfig_price_tier_5_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshpricingconfig',
            name='fee_annual_report_not_submitted',
        ),
        migrations.RemoveField(
            model_name='poshpricingconfig',
            name='fee_no_external_member',
        ),
        migrations.RemoveField(
            model_name='poshpricingconfig',
            name='fee_no_ic',
        ),
        migrations.RemoveField(
            model_name='poshpricingconfig',
            name='fee_no_posh_policy',
        ),
        migrations.RemoveField(
            model_name='poshpricingconfig',
            name='fee_not_she_box_registered',
        ),
        migrations.RemoveField(
            model_name='poshpricingconfig',
            name='price_tier_4_max',
        ),
        migrations.RemoveField(
            model_name='poshpricingconfig',
            name='price_tier_4_rate',
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_annual_report_t0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_annual_report_t1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_annual_report_t2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_annual_report_t3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_no_external_member_t0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_no_external_member_t1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_no_external_member_t2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_no_external_member_t3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_no_ic_t0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_no_ic_t1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_no_ic_t2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_no_ic_t3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_no_posh_policy_t0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_no_posh_policy_t1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_no_posh_policy_t2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_no_posh_policy_t3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_not_she_box_t0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_not_she_box_t1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_not_she_box_t2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_not_she_box_t3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='poshpricingconfig',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='poshpricingconfig',
            name='price_tier_3_max',
            field=models.IntegerField(default=200, help_text='Max employees for Tier 4 (101-200)'),
        ),
    ]
