# Generated by Django 6.0.3 on 2026-04-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_poshregistration_require_external_member_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshregistration',
            name='annual_report_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
