# Generated by Django 6.0.3 on 2026-04-09 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_poshregistration_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshpricingconfig',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='Global GST percentage', max_digits=5),
        ),
        migrations.CreateModel(
            name='POCSOPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_drafting_cost', models.DecimalField(decimal_places=2, default=5000.0, help_text='Cost for drafting Child Protection Policy', max_digits=10)),
                ('committee_formation_cost', models.DecimalField(decimal_places=2, default=5000.0, help_text='Cost for Committee Formation', max_digits=10)),
                ('teaching_cost_per_teacher', models.DecimalField(decimal_places=2, default=136.0, max_digits=10)),
                ('teaching_cost_offline', models.DecimalField(decimal_places=2, default=12000.0, max_digits=10)),
                ('teaching_cost_online', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('non_teaching_cost_per_staff', models.DecimalField(decimal_places=2, default=91.0, max_digits=10)),
                ('non_teaching_cost_offline', models.DecimalField(decimal_places=2, default=8000.0, max_digits=10)),
                ('non_teaching_cost_online', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('vendor_policy_cost', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('transport_safety_cost', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('student_safety_cost_per_child', models.DecimalField(decimal_places=2, default=55.0, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, help_text='Global GST percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only ONE active config should exist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POCSO Pricing Configuration',
                'verbose_name_plural': 'POCSO Pricing Configurations',
            },
        ),
        migrations.CreateModel(
            name='POCSORegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=255)),
                ('students_count', models.IntegerField(default=0)),
                ('teachers_count', models.IntegerField(default=0)),
                ('non_teaching_staff_count', models.IntegerField(default=0)),
                ('housekeeping_staff_count', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('has_policy', models.BooleanField(default=False)),
                ('has_committee', models.BooleanField(default=False)),
                ('teaching_staff_trained', models.BooleanField(default=False)),
                ('teaching_training_mode', models.CharField(blank=True, choices=[('PER_PERSON', 'Per Person'), ('OFFLINE', 'Offline (up to 100)'), ('ONLINE', 'Online (up to 100)')], max_length=20, null=True)),
                ('non_teaching_staff_trained', models.BooleanField(default=False)),
                ('non_teaching_training_mode', models.CharField(blank=True, choices=[('PER_PERSON', 'Per Person'), ('OFFLINE', 'Offline (up to 100)'), ('ONLINE', 'Online (up to 100)')], max_length=20, null=True)),
                ('vendors_access_premises', models.BooleanField(default=False)),
                ('has_vendor_policy', models.BooleanField(default=False)),
                ('has_transport', models.BooleanField(default=False)),
                ('aware_of_transport_policy', models.BooleanField(default=False)),
                ('students_trained', models.BooleanField(default=False)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='pocso_payments/')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pocso_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
