# Generated by Django 6.0.3 on 2026-04-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_poshpricingconfig_gst_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocsopricingconfig',
            name='committee_formation_cost',
        ),
        migrations.RemoveField(
            model_name='pocsopricingconfig',
            name='non_teaching_cost_offline',
        ),
        migrations.RemoveField(
            model_name='pocsopricingconfig',
            name='non_teaching_cost_online',
        ),
        migrations.RemoveField(
            model_name='pocsopricingconfig',
            name='non_teaching_cost_per_staff',
        ),
        migrations.RemoveField(
            model_name='pocsopricingconfig',
            name='policy_drafting_cost',
        ),
        migrations.RemoveField(
            model_name='pocsopricingconfig',
            name='student_safety_cost_per_child',
        ),
        migrations.RemoveField(
            model_name='pocsopricingconfig',
            name='teaching_cost_offline',
        ),
        migrations.RemoveField(
            model_name='pocsopricingconfig',
            name='teaching_cost_online',
        ),
        migrations.RemoveField(
            model_name='pocsopricingconfig',
            name='teaching_cost_per_teacher',
        ),
        migrations.RemoveField(
            model_name='pocsopricingconfig',
            name='transport_safety_cost',
        ),
        migrations.RemoveField(
            model_name='pocsopricingconfig',
            name='vendor_policy_cost',
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_committee_t0',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_committee_t1',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_committee_t2',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_committee_t3',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_committee_t4',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_policy_t0',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_policy_t1',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_policy_t2',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_policy_t3',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_policy_t4',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_student_training_t0',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_student_training_t1',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_student_training_t2',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_student_training_t3',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_student_training_t4',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_training_t0',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_training_t1',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_training_t2',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_training_t3',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_training_t4',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_transport_t0',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_transport_t1',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_transport_t2',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_transport_t3',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_transport_t4',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_vendor_t0',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_vendor_t1',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_vendor_t2',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_vendor_t3',
            field=models.DecimalField(decimal_places=2, default=25000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='fee_no_vendor_t4',
            field=models.DecimalField(decimal_places=2, default=35000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='price_tier_0_max',
            field=models.IntegerField(default=10, help_text='Max headcount for Tier 1'),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='price_tier_1_max',
            field=models.IntegerField(default=25, help_text='Max headcount for Tier 2'),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='price_tier_2_max',
            field=models.IntegerField(default=100, help_text='Max headcount for Tier 3'),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='price_tier_3_max',
            field=models.IntegerField(default=200, help_text='Max headcount for Tier 4'),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='price_tier_4_max',
            field=models.IntegerField(default=500, help_text='Max headcount for Tier 5'),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='staff_rate_t0',
            field=models.DecimalField(decimal_places=2, default=91.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='staff_rate_t1',
            field=models.DecimalField(decimal_places=2, default=91.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='staff_rate_t2',
            field=models.DecimalField(decimal_places=2, default=91.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='staff_rate_t3',
            field=models.DecimalField(decimal_places=2, default=91.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='staff_rate_t4',
            field=models.DecimalField(decimal_places=2, default=91.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='student_rate_t0',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='student_rate_t1',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='student_rate_t2',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='student_rate_t3',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='student_rate_t4',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='teacher_rate_t0',
            field=models.DecimalField(decimal_places=2, default=136.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='teacher_rate_t1',
            field=models.DecimalField(decimal_places=2, default=136.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='teacher_rate_t2',
            field=models.DecimalField(decimal_places=2, default=136.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='teacher_rate_t3',
            field=models.DecimalField(decimal_places=2, default=136.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pocsopricingconfig',
            name='teacher_rate_t4',
            field=models.DecimalField(decimal_places=2, default=136.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pocsopricingconfig',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
