# Generated by Django 6.0.3 on 2026-04-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "home",
            "0031_rename_fee_no_committee_t0_pocsopricingconfig_fee_no_committee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="poshregistration",
            name="require_ic_training",
            field=models.BooleanField(default=False),
        ),
    ]
