# Generated by Django 6.0.3 on 2026-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_poshregistration_require_ic_training"),
    ]

    operations = [
        migrations.AddField(
            model_name="poshregistration",
            name="requested_expert_led_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="poshregistration",
            name="requested_ic_training_mode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
