# Generated by Django 6.0.3 on 2026-04-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_poshregistration_requested_expert_led_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_21_23_t0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_21_23_t1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_21_23_t2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_21_23_t3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_21_23_t4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_24_25_t0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_24_25_t1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_24_25_t2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_24_25_t3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_24_25_t4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_other_t0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_other_t1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_other_t2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_other_t3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_history_other_t4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_online_t0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_online_t1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_online_t2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_online_t3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_online_t4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_physical_t0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_physical_t1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_physical_t2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_physical_t3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_physical_t4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_virtual_t0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_virtual_t1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_virtual_t2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_virtual_t3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='poshpricingconfig',
            name='fee_ic_requested_virtual_t4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
