# Generated by Django 6.0.3 on 2026-04-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0035_alter_pocsoregistration_non_teaching_training_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pocsoregistration",
            name="housekeeping_staff_count",
        ),
    ]
