# Generated by Django 5.2.13 on 2026-04-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0039_add_payment_verified_email_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="tier_key",
            field=models.CharField(
                choices=[
                    ("PAY_NOW", "Payment Received Confirmation"),
                    ("PAYMENT_VERIFIED", "Payment Verified – Onboarding Confirmed"),
                    ("EMPLOYEE_WELCOME", "Employee Welcome – Account Credentials"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
