# Generated by Django 5.2.13 on 2026-04-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0040_add_employee_welcome_email_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
