# Generated by Django 6.0.4 on 2026-05-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_add_designation_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterLogoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_path', models.CharField(max_length=500)),
                ('logo_x', models.FloatField(default=2.0)),
                ('logo_y', models.FloatField(default=2.0)),
                ('logo_width', models.FloatField(default=15.0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_configs', to='home.organization')),
            ],
            options={
                'unique_together': {('organization', 'poster_path')},
            },
        ),
    ]
