# Generated by Django 6.0.4 on 2026-05-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_posterlogoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterlogoconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='poster_logos/'),
        ),
    ]
