name: Cleanup Artifacts

on:
  schedule:
    - cron: '0 0 1 * *' # Monthly
  workflow_dispatch:

permissions:
  packages: write

jobs:
  clean-ghcr:
    name: Clean GHCR Old Images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'ohs'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
        continue-on-error: true
